/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#8d7164",
        "surface-dim": "#d2d9f4",
        "tertiary": "#006c49",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb692",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#281900",
        "surface-bright": "#faf8ff",
        "secondary-fixed": "#ffdeac",
        "on-tertiary-container": "#003a25",
        "surface": "#faf8ff",
        "on-primary-fixed": "#341100",
        "secondary": "#7e5700",
        "on-primary": "#ffffff",
        "tertiary-container": "#00af79",
        "error-container": "#ffdad6",
        "surface-container-highest": "#dae2fd",
        "inverse-on-surface": "#eef0ff",
        "surface-container-high": "#e2e7ff",
        "surface-tint": "#9f4200",
        "on-primary-fixed-variant": "#7a3000",
        "secondary-container": "#feb300",
        "on-error": "#ffffff",
        "surface-container": "#eaedff",
        "on-surface-variant": "#594136",
        "on-tertiary": "#ffffff",
        "on-background": "#131b2e",
        "tertiary-fixed-dim": "#4edea3",
        "surface-variant": "#dae2fd",
        "primary": "#9f4200",
        "on-secondary-container": "#6a4800",
        "primary-container": "#ff6d00",
        "on-primary-container": "#582100",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-fixed": "#002113",
        "inverse-surface": "#283044",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#ffb692",
        "primary-fixed": "#ffdbcb",
        "outline-variant": "#e2bfb0",
        "on-surface": "#131b2e",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffba38",
        "on-secondary-fixed-variant": "#604100",
        "background": "#faf8ff",
        // Extended student brand colors
        "orange-brand": "#ff6d00",
        "mint-value": "#10b981",
        "navy-slate": "#0f172a"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "sm": "0.5rem",
        "md": "1.5rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        "gutter-sm": "0.75rem",
        "margin": "1.25rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter": "1rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "sans": ["Plus Jakarta Sans", "Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "700" }],
        "headline-lg": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "headline-md": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "headline-xl": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.025em", "fontWeight": "800" }],
        "headline-sm": ["16px", { "lineHeight": "22px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
